#!/usr/bin/env ruby -w

# require_relative '../../../test-support'

module Skylab::TanMan::TestSupport::Sexp

  class Grammars::Grammar03 < self::Grammar

    # everything is magic
  end
end

if __FILE__ == $PROGRAM_NAME
  Skylab::TanMan::TestSupport::Sexp::Grammars::Grammar03.new( ARGV ).execute
end
