#!/usr/bin/env zsh  #just-for-syntax-highlighting

part-repo $* || return $?
part-ls-files $* || return $?
part-show $* || return $?
part-show-negatives $* || return $?
part-log-follow $* || return $?
