#!/usr/bin/env zsh  #just-for-syntax-highlighting

typeset -a rest ; rest=($*)

-print-component-node-description () {
  serr
  serr "$( -hdr "description:" ) build specific parts by name"
}

-say-component-node-child-moniker () {
  print part
}

-say-component-node-function-name-prefix () {
  print part-
}

-say-component-node-args () {
  typeset s="$( -component-node-first-arg-moniker )"
  print $s
}

if (( 2 < $#rest )) ; then
  -print-component-node-splay-usage-line "too many arguments. "
  -print-component-node-splay-invite
  return $gv_err_extra_param
fi

component-node-splay
