#!/usr/bin/env zsh  #just-for-syntax-highlighting

serr "pretending to do 'part show'"

return $gv_success

typeset transient_iam transient_out transient_err
-build-negatives-inside-of-directory () {
  transient_out=tmp.show.456456.out.txt
  transient_err=tmp.show.456456.err.txt
  transient_iam=tmp.show.456456.iam.txt
  $vcs_exe show --numstat --pretty=tformat:%ai 456456 -- \
    1>"$transient_out" 2>"$transient_err"
  typeset exitstatus=$?
  print "exitstatus $exitstatus" > "$transient_iam"
}
