#!/usr/bin/env python3 -W error::Warning::0

import socket

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:

    s.connect(('0.0.0.0', 50007))

    s.sendall(b'Hello world')
    msg = s.recv(1024)

print('received: ', repr(msg))

# #born
