#!/usr/bin/env python3 -W error::Warning::0

import socket

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind(('0.0.0.0', 50007))
    s.listen(1)  # ..
    print('about to block waiting for connection')
    con, adr = s.accept()
    with con:
        print('connected by', adr)
        while True:
            msg = con.recv(1024)
            if not msg:
                print('no data. breaking.')
                break
            con.sendall(msg)

# #born
