#!/usr/bin/env bash

datadir="test/doc-test/data"
if [[ ! -d "$datadir" ]] ; then
  echo "no data dir - $datadir"
  exit 1
fi

eval $( "lib/skylab/test-support/script/bash-value-export" )
  # the above sets `test_file_tail`

cat "$datadir/files" | while read line
do
  read file out <<<$(IFS=' '; echo "$line")
  if [[ ! -e "$file" ]] ; then
    echo "not found - $file"
  else
    haha=$( ruby -e "a = \"$file\".split( '/' ) ; puts \"#{a[2]} #{ a[3..-1].join('/')[ 0..-4 ]}\"" )
    read r1 r2 <<<$(IFS=' '; echo "$haha")
    i="tmx regret doc-test -vv $file"
    if [ -z "$out" ] ; then
      out="lib/skylab/$r1/test/$r2$test_file_tail"
    fi
    _cmd="$i > $out"
    echo "$_cmd"
    eval "$i" > "$out"
  fi
done

me="test/doc-test/script/compile: "
echo "${me}done."
