#!/usr/bin/env ruby -w

require_relative 'test-support'

module Skylab::TanMan::TestSupport::Models::DotFile

  class Client

    def initialize
      @on_event_selectively = -> * i_a, & ev_p do
        ev = ev_p[]
        if :using_parser_files != ev.terminal_channel_i
          raise ev.to_exception
        end
      end
    end

    def parse_file input_file_path
      _doc_controller_via_name_value_pair( :input_path, input_file_path ).graph_sexp
    end

    def parse_string input_string
      _doc_controller_via_name_value_pair( :input_string, input_string ).graph_sexp
    end

    def _doc_controller_via_name_value_pair sym, x

      TanMan_::Models_.class

      bx = TanMan_::Callback_::Box.new

      bx.add sym, TanMan_.lib_.basic.trio( x, true,

        TanMan_::Model_::Document_Entity::IO_PROPERTIES__.fetch( sym ) )

      TanMan_::API.application_kernel.silo( :dot_file ).
        document_controller_via_trio_box bx, & @on_event_selectively
    end
  end
end

if __FILE__ == $PROGRAM_NAME
  ::Skylab::TanMan::TestSupport::Models::DotFile::Client.new.invoke ARGV
end
