#!/usr/bin/env python3

# recsel -C -pDuration tilex-doc/890.C.youtube-tutorial-dim-sum.rec | here

from sys import stdin
secs_total = 0

if stdin.isatty():
    print(f"usage: recsel -C -pDuration tilex-doc/890.C.foo.rec | {__file__}")
    exit(3)

count = 0
for line in stdin:
    line = line.strip()
    label, mins, secs = line.split(':')
    assert 'Duration' == label
    count += 1
    mins = int(mins)
    secs = int(mins)
    secs_total += 60 * mins
    secs_total += secs

mins, secs = divmod(secs_total, 60)
hours, mins = divmod(mins, 60)

print(f"total: %1d:%02d:%02d in %d videos" % (hours, mins, secs, count))

# #born
