#!/usr/bin/env zsh

if [ "$1" != "" ] ; then
  echo "usage: $0"
  exit 5
fi

file1=lib/skylab/beauty_salon/crazy-town-magnetics-/selector-via-string/grammar-in-c.rl
ragel "$file1"
d=$?
echo -n "."
if [ 0 != $d ] ; then
  echo " (^ got exitstatus $d from 'ragel $file1)"
  exit d
fi

file2=lib/skylab/beauty_salon/crazy-town-magnetics-/selector-via-string/grammar-in-c.c
gcc "$file2"
d=$?
if [ 0 != $d ] ; then
  echo " (^ get exitstatus $d from 'gcc $file2')"
  exit d
fi
echo -n "."
echo " rebuilt."
