#!/usr/bin/env zsh

# read [#017] the fixtures building narrative

typeset me=$0; typeset -a rest; rest=($*)

# meh:
typeset x=$(dirname $me)
typeset testdir=$(dirname $x)

source "$testdir/zsh-lib/init-component-node.zsh"

typeset child_nodes_dir=$component_node_local_top_dir/vcs-adapters

-print-component-node-description () {
  serr
  serr "$( -hdr description: ) builds assets and their parts typically"
  serr "             for use in generating fixutre output snapshots."
}

component-node-splay
