#!/usr/bin/env ruby -w

## ensure that we are working from the gemfile
ENV['BUNDLE_GEMFILE'] ||= File.
  expand_path( "../../../../../../Gemfile", __FILE__ )

require 'rubygems'
require 'bundler/setup'
## end

require_relative '../../core'

# read [#018] the system call fixtures server narrative

Skylab::GitViz::Test_Lib_::Mock_System::Fixture_Server.
  new( $stderr, 5555, ::ARGV ).run
