#!/usr/bin/env ruby -w

require_relative '../../core'

# read [#018] the system call fixtures server narrative

Skylab::GitViz::Test_Lib_::Mock_System::Fixture_Server.
  new( $stderr, 5555, ::ARGV ).run
