STORAGE_ADAPTER_CAN_LOAD_DIRECTORIES = False
STORAGE_ADAPTER_CAN_LOAD_SCHEMALESS_SINGLE_FILES = False
STORAGE_ADAPTER_IS_AVAILABLE = False
STORAGE_ADAPTER_UNAVAILABLE_REASON = (
    "sqlite storage adapter is WIP and stashed")

# #born empty
