#!/usr/bin/env python3

"""
plot the dates of woody allen movies in a one-dimensional scatterplot

broadly there are 3 steps to this:

    - download the html (write it to a tmp file)

    - scrape the html for the year of the movies (write it to a json file)

    - turn the list of years into a MINIMALLY simple visualization
      (a "one dimensional scatterplot")
"""


from os import path as os_path


# at #history-B.2 increased expected number of tables from 4 to 6
# at #history-A.2 [#676] worked but:
# NOTE - this writes tempfiles so take that into account when you cover


_doc = __doc__  # grab the above as our UI docstring before below


# TODO (we don't yet want these in a versionsed Pipfile because it would
# be a very weak development dependency, and we want to hold off on any
# dependencies for now..)


"""
dependencies (TODO):
    - matplotlib       2.1.2
    - numpy            1.14.1
"""


url = 'https://en.wikipedia.org/wiki/Woody_Allen_filmography'


# [#007.3]

tmp_numbers_file = 'tmp.woody-allen.numbers.list'
tmp_html_file = 'tmp.woody-allen.page.html'
_here = 'z/_CACHED_FOR_SCRAPING_'  # #[#007.3]
tmp_numbers_file = os_path.join(_here, tmp_numbers_file)
tmp_html_file = os_path.join(_here, tmp_html_file)
_fixture_html = 'data_pipes_test/fixture-files/500-html/5881-woody-allen.html'


def _formals():
    yield '--use-numpy', 'do the full monty. requires things'
    yield '-t', '--test', 'test self'
    yield '-h', '--help', 'this screen'


def _CLI(stdin, stdout, stderr, argv):  # #testpoint
    from script_lib.cheap_arg_parse import cheap_arg_parse as func
    return func(_do_CLI, stdin, stdout, stderr, argv, _formals())


def _do_CLI(sin, sout, serr, do_use_numpy, do_test, rscer):
    def main():
        self.use_path = procure_html_file_on_the_filesystem()
        write_the_numbers_file_to_the_workspace()
        return _display_thing(client, ws, do_use_numpy)

    def write_the_numbers_file_to_the_workspace():
        if ws.tmp_numbers_file_exists:
            return client.info('(using {})', ws.tmp_numbers_file)
        return _write_numbers_file(ws, client)

    def procure_html_file_on_the_filesystem():
        if ws.tmp_html_file_exists:
            client.info('(using {})', ws.tmp_html_file)
            return ws.tmp_html_file
        if _write_html_file(client, ws):
            return tmp_html_file
        raise stop()

    client = _Client(sout, serr)
    ws = _MutableWorkspace('for_test' if do_test else 'for_production')
    self = main  # watch the world burn

    class stop(RuntimeError):
        pass
    try:
        return main()
    except stop:
        return 5


_do_CLI.__doc__ = _doc


def _display_thing(client, ws, do_thing):

    float_a = tuple(_floats_via_file(ws))
    if do_thing:
        return _display_thing_using_numpy(client, float_a)
    return _display_thing_simply(client, float_a)


def _display_thing_using_numpy(client, float_a):
    """(adapted from K.-Michael Aye's work stack overflow)"""

    import numpy as np
    import matplotlib.pyplot as pp

    val = 0.  # this is the value where you want
    # the data to appear on the y-axis.

    ar = [float_a]
    pp.plot(ar, np.zeros_like(ar) + val, 'x')
    client.info('(showing. close window there to return.)')
    pp.show()
    return _exitstatus_for_success


def _display_thing_simply(client, float_a):
    io = client.stdout
    count = 0
    for f in float_a:
        count += 1
        io.write('%0.2f\n' % f)
    client.info('({} items total)', count)
    return _exitstatus_for_success


def _floats_via_file(ws):
    import json
    with ws.open_tmp_numbers_file_for_reading() as fh:
        for line in fh:
            _row = json.loads(line)
            yield float(_row['year'])


def _write_numbers_file(ws, client):
    from bs4 import BeautifulSoup
    with ws.open_tmp_html_file_for_reading() as fh:
        soup = BeautifulSoup(fh, 'html.parser')

    tables = soup.find_all(None, 'wikitable')
    ln = len(tables)
    exp = 6
    if exp != ln:
        client.error('expected {} had {} tables', exp, ln)
        return False

    table = tables[0]
    del tables

    itr = iter(table.find_all('tr'))
    next(itr)  # skip header row (1 of 2)
    next(itr)  # skip header row (2 of 2)

    def f():
        """there's always only ever one movie per table row. however, when

        there's multiple movies in a year, this little dance happens:
        there's one row whose year cell has a greater-than-one `rowspan`.
        then, the N-1 subsequent rows will each have a number of cels that
        is *one less* than normal number (because they each don't-need-and-
        must-not-have their own year cel).

        the way we handle this below is rough with redundancy because it's
        a one-off, but note there are three `yields` below for the three
        kinds of rows we will encounter (1: easy rows, 2: the first row in
        group, and 3: the subsequent rows in a group.)
        """

        for tr in itr:
            tds = tr.find_all('td')
            year_td = tds[0]
            year = int(year_td.text)
            rowspan_s = year_td.get('rowspan')
            if rowspan_s is None:
                yield(0.5 + year, tds[1].text)
            else:
                num_rows = float(rowspan_s)
                numerator_int = 1
                denom_float = num_rows + 1   # ick: 3 rows: 1/4 2/4 3/4

                yield((1.0*numerator_int/denom_float)+year, tds[1].text)
                while True:
                    numerator_int += 1
                    tr = next(itr)
                    tds = tr.find_all('td')
                    yield((1.0*numerator_int/denom_float)+year, tds[0].text)

                    if numerator_int == num_rows:
                        break

    import json
    count = 0

    with ws.open_tmp_numbers_file_for_writing() as fh:
        for (year_f, movie_name) in f():
            _json = json.dumps({'year': year_f, 'movie_title': movie_name})
            fh.write(_json + '\n')
            count += 1

    client.info("wrote {} lines to {}", count, ws.tmp_numbers_file)
    return True


def _write_html_file(client, ws):
    import requests
    with open(tmp_html_file, 'w') as fh:
        r = requests.get(url)
        status_code = r.status_code
        if 200 == status_code:
            _bytes = fh.write(r.text)
            client.info('wrote {} ({} bytes)', tmp_html_file, _bytes)
            ok = True
        else:
            client.error('bad status code: {}', status_code)
            ok = False
    if not ok:
        ws.remove_file(tmp_html_file)
    return ok


class _Client:
    """("modality" "injection")"""

    def __init__(self, stdout, stderr):
        self.stdout = stdout
        self.stderr = stderr

    def error(self, fmt, *args):
        self._same(fmt, args)

    def info(self, fmt, *args):
        self._same(fmt, args)

    def _same(self, fmt, args):
        self.stderr.write(fmt.format(*args)+'\n')


def ting_ting(orig_f):  # #decorator
    def use_f(self):
        orig_f(self)
        if self._is_for_production:
            attr = ''.join((attr_head, '__when_production'))
        else:
            attr = ''.join((attr_head, '__when_testing'))
        return getattr(self, attr)()
    attr_head = orig_f.__name__
    return use_f


class _MutableWorkspace:  # HUGE EXPERIMENT so code-heavy 😢

    def __init__(self, which):
        self._is_for_production = ('for_test', 'for_production').index(which)
        self._init()

    @ting_ting
    def _init(self):
        self.tmp_numbers_file = tmp_numbers_file

    def _init__when_testing(self):
        self.tmp_html_file = _fixture_html
        self._fake_filesystem_lol = {}

    def _init__when_production(self):
        self.tmp_html_file = tmp_html_file

    # ==

    @ting_ting
    def open_tmp_numbers_file_for_writing(self):
        pass

    def open_tmp_numbers_file_for_writing__when_testing(self):
        lines = []

        class fh_proxy:  # #class-as-namespace
            def write(chars):
                assert fh_proxy._is_open
                lines.append(chars)  # ..
                return len(chars)
            _is_open = True

        @_context_manager
        def cm():
            yield fh_proxy
            fh_proxy._is_open = False
            self._fake_filesystem_lol[tmp_numbers_file] = tuple(lines)
        return cm()

    def open_tmp_numbers_file_for_writing__when_production(self):
        return open(tmp_numbers_file, 'w')

    # ==

    @ting_ting
    def open_tmp_numbers_file_for_reading(self):
        pass

    def open_tmp_numbers_file_for_reading__when_testing(self):
        @_context_manager
        def cm():
            yield iter(self._fake_filesystem_lol[tmp_numbers_file])
        return cm()

    def open_tmp_numbers_file_for_reading__when_production(self):
        return open(tmp_numbers_file)

    # ==

    @property
    @ting_ting
    def tmp_numbers_file_exists(self):
        pass

    def tmp_numbers_file_exists__when_testing(self):
        return tmp_numbers_file in self._fake_filesystem_lol

    def tmp_numbers_file_exists__when_production(self):
        return self.path_exists(tmp_numbers_file)

    # ==

    def open_tmp_html_file_for_reading(self):
        return open(self.tmp_html_file, 'r')

    # ==

    @property
    @ting_ting
    def tmp_html_file_exists(self):
        pass

    def tmp_html_file_exists__when_testing(self):
        return True

    def tmp_html_file_exists__when_production(self):
        return self.path_exists(tmp_html_file)

    # ==

    def remove_file(self, path):
        import os
        os.remove(path)

    def path_exists(self, path):
        import os
        return os.path.exists(path)


def _context_manager(orig_f):
    from contextlib import contextmanager as decorator
    return decorator(orig_f)


def xx(msg=None):
    raise RuntimeError(''.join(('write me', *((': ', msg) if msg else ()))))


_exitstatus_for_success = 0


if __name__ == '__main__':
    import sys as o
    exit(_CLI(o.stdin, o.stdout, o.stderr, o.argv))

# #history-A.2 refactor to cheap arg parse
# #history-A.1
# #born.
