#!/usr/bin/env zsh  #just-for-syntax-highlighting

-say-component-node-function-name-prefix-infix () {
  print -- -asset-
}

-say-build-script-for-child-node () {
  print -- $component_node_local_top_dir/asset-script/for-mock-$1/script/build
}


  typeset -a arr ; arr=(${(f)"$(-say-each-component-child-node-slug)"})
  typeset r=$gv_success rr x
  for x ($arr) ; do
    dispatch-target-to-child-build-script all $x $*
    rr=$?
    (( $gv_success == $rr )) || r=$rr
  done
  return $r
