#!/usr/bin/env zsh  #just-for-syntax-highlighting

-say-component-node-function-name-prefix-infix () {
  print -- -asset-
}

-say-build-script-for-child-node () {
  print -- $component_node_local_top_dir/asset-script/for-mock-$1/script/build
}

dispatch-target-and-args-to-all all "${*[@]}"
