#!/usr/bin/env zsh

file=$1 ; lineno=$2 ; indent=$3 ; const=$4 ; version=$5

serr () {
  print $*
}

if (( 5 < $# )) ; then
  serr "usage: $1 <file> <lineno> <indent> <const> <version>"
  exit 3
fi

serr -n "rewriting one line in $file .."
ed -s $file <<END_OF_ED
$lineno,${lineno}c
${indent}${const} = '${version}'
.
w
END_OF_ED

serr " done."
serr "like us, the above change should probably be committed"\
 "(veresion $version)."
