#!/usr/bin/env zsh  #just-for-syntax-highlighting

# overwrite the partent's variable of the same name. slip 'part' in there
# to tell the asset node that this is a part request.

typeset x="$1"
(( 0 < $# )) && shift
typeset -a rest ; rest=("$x" part $*)

-print-component-node-description () {
  serr
  serr "$( -hdr "description:" ) build one asset [possibly just its sub part]"
}
-say-component-node-args () {
  typeset s="$( -component-node-first-arg-moniker )"
  print "part $s [..]"
}
-say-component-node-child-moniker () {
  print "asset"
}
-say-component-node-function-name-prefix-infix () {
  print -- '-asset-'
}

component-node-splay
