#!/usr/bin/env ruby -w

load File.expand_path( '../02-build-the-manifest', __FILE__ )

module Skylab::GitViz::TestSupport

  module FixtureStoriesForGit::Story_01

    class Normalize_the_manifest < Build_the_manifest

      def init_path_ivars_via_build_file_path file
        super
        @raw_manifest_path = @path
        @path = ::File.join @here, 'commands.ogdl'
        NIL_
      end

      def execute
        @main_mock_repo_path ||= '/the/repo'
        init_name_mappings
        super
      end

      attr_writer :main_mock_repo_path

      def work

        _System = Home_.lib_.system_lib

        _thing = _System::Doubles::Stubbed_System.
          readable_writable_via_OGDL_path @raw_manifest_path

        st = _thing.to_command_stream

        norm = Here_::Magnetics_::Command_via_Arguments.new(
          @name_mappings,
          @tmpdir,
          @main_mock_repo_path,
          @serr )

        begin

          cmd = st.gets
          cmd or break
          _cmd_ = norm.against cmd
          @sess.receive_command _cmd_

          redo
        end while nil

        NIL_
      end
    end
  end
end

if $PROGRAM_NAME == __FILE__

  _ok = Skylab::GitViz::TestSupport::FixtureStoriesForGit::Story_01::Normalize_the_manifest[
    $stdin, $stdout, $stderr, $PROGRAM_NAME, ARGV, __FILE__ ]

  exit _ok ? 0 : 5
end
