#!/usr/bin/env ruby -w

path, fake_SHA = ARGV

if ! fake_SHA
  puts "usage: #{ ::File.basename $PROGRAM_NAME } <file> <fake_SHA>" ; exit 1
end

first_ = case fake_SHA
when '012012' ; '2014-01-04 02:16:00 -0500'
when '345345' ; '2014-01-04 18:33:24 -0500'
when '123123' ; '2014-01-05 04:03:24 -0500'
when '234234' ; '2014-01-05 10:33:24 -0500'
end

if ! first_
  puts "there is no fake date for fake SHA: #{ fake_SHA.inspect }" ; exit 1
end

fh = ::File.open path, 'r+'

first = fh.gets

if /\A\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} [-+]\d{4}\n\z/ =~ first
  rest = fh.read
  fh.rewind
  fh.puts first_
  fh.write rest
  puts "  normalized dateline from (#{ first.chomp }) to (#{ first_ }). done."
  fh.close
  exit 0
else
  puts "didn't look like dateline: #{ first.inspect }"
  fh.close
  exit 3
end
