#!/usr/bin/env ruby -w

# (..)

module Skylab::TanMan::TestSupport

  class Models::Dot_File::Client

    def initialize

      @on_event_selectively = -> * i_a, & ev_p do

        ev = ev_p[]

        if :using_parser_files != ev.terminal_channel_i
          raise ev.to_exception
        end
      end
    end

    def parse_file input_file_path
      _doc_controller_via_name_value_pair( :input_path, input_file_path ).graph_sexp
    end

    def parse_string input_string
      _doc_controller_via_name_value_pair( :input_string, input_string ).graph_sexp
    end

    def _doc_controller_via_name_value_pair sym, x

      Home_::Models_.class

      bx = Home_::Common_::Box.new

      bx.add sym, Common_::Qualified_Knownness.via_value_and_association( x,
        Home_::Model_::DocumentEntity::IO_PROPERTIES__.fetch( sym ) )

      Home_.application_kernel_.silo( :dot_file ).
        document_controller_via_qualified_knownness_box bx, & @on_event_selectively
    end
  end
end

if __FILE__ == $PROGRAM_NAME
  ::Skylab::TanMan::TestSupport::Models::DotFile::Client.new.invoke ARGV
end
