#!/usr/bin/env ruby -w

# (..)

module Skylab::TanMan::TestSupport

  class Models::Dot_File::Client

    def initialize invo

      @listener = -> * sym_a, & ev_p do

        if :using_parser_files == sym_a.last
          NOTHING_
        elsif :creating == sym_a.last
          NOTHING_  # near [#086]
        else
          _ev = ev_p[]
          _ex = _ev.to_exception
          raise _ex
        end
      end

      @__invocation = invo
    end

    def parse_file input_file_path, & sess
      _graph_sexp_via :input_path, input_file_path, & sess
    end

    def parse_string input_string, & sess
      _graph_sexp_via :input_string, input_string, & sess
    end

    def _graph_sexp_via sym, x

      # _asc = Home_::DocumentMagnetics_::CommonAssociations.common_IO_parameters.dereference sym
      # _qkn = Common_::QualifiedKnownKnown[ x, _asc ]
      # (above worked but was overkill :#history-A.1)

      _qkn = Common_::QualifiedKnownKnown.via_value_and_symbol x, sym

      _ref = Home_::DocumentMagnetics_::
        ByteStreamReference_via_QualifiedKnownness_and_ThroughputDirection.call(
          _qkn, :input )

      x = nil
      sane_mode = block_given?

      Home_::Models_::DotFile::DigraphSession_via_THESE.call_by do |o|

        o.session_by do |dc|
          if sane_mode
            x = yield dc
          else
            x = dc  # yikes
          end
          true
        end

        o.be_read_only_not_read_write_
        o.byte_stream_reference = _ref
        o.microservice_invocation = @__invocation
        o.listener = @listener
      end

      if sane_mode
        x
      else
        x.graph_sexp  # yikes - outside of the session but meh
      end
    end
  end
end

if __FILE__ == $PROGRAM_NAME

  self._CHANGED__readme__  # this changed long before this writing. currently
  # the subject is not useful for running from the command line, however it
  # is eminently useful for parsing dotfiles from tests.

  ::Skylab::TanMan::TestSupport::Models::DotFile::Client.new( ARGV ).execute
end
# :#history-A.1 (probably tmp)
