#!/usr/bin/env ruby -w

require_relative '../test-support'

module ::Skylab::TanMan::TestSupport::Sexp
  class Grammars::Grammar70_SimpleRecursiveList < self::Grammar
    # everything is magic
  end
end

if __FILE__ == $PROGRAM_NAME
  ::Skylab::TanMan::TestSupport::Sexp::Grammars::
    Grammar70_SimpleRecursiveList.new.invoke ARGV
end
