#!/usr/bin/env ruby -w

require_relative '../../core'
mod = ::Skylab::CssConvert
runtime  = mod::CLI.new.request_runtime
parser = mod::CssParser.new(runtime)
input = $stdin.tty? ? ARGV.join(" ") : $stdin.read
puts input.inspect
result = parser.parse_string(input)
# puts "response: "+result.inspect
puts "num terminal failures: #{parser.terminal_failures.size}"
if true
  puts "SKIPPING REST OF TEST FOR NOW"
elsif result
  puts "got result: "
  require 'pp'
  ::PP.pp result.tree
  puts "unparsed:"
  puts result.tree.unparse.inspect
else
  puts "got failure:"
  puts parser.failure_reason
end
