#!/usr/bin/env ruby -w

require_relative '../../core'

module Skylab::CssConvert
  module VizTest
  end
  module VizTest::InstanceMethods
    def build_request_runtime
      CssConvert::CLI.new.request_runtime
    end
    def emit _, msg
      $stderr.puts msg
    end
    def error msg
      emit(:error, msg)
      false
    end
    def resolve_input_string argv=ARGV, stdin=$stdin
      if stdin.tty?
        if 1 == argv.length
          File.read(argv.first)
        else
         error("no. expecting <filename> or stdin")
        end
      elsif argv.empty?
        stdin.read.chomp
      else
        error("no. can't have argv and stdin.")
      end
    end
  end

  class VizTest::Dix
    include VizTest::InstanceMethods
    def invoke
      parser = CssConvert::DirectivesParser.new(build_request_runtime)
      input = resolve_input_string or return
      # puts "input: #{input.inspect}"
      result = parser.parse_string(input)
      # puts "result was: "+result.inspect
      puts "(num terminal failures: #{parser.parser.terminal_failures.length})"
      if result
        require 'pp'
        puts "result tree:"
        ::PP.pp result
      else
        puts "got no result.."
        puts parser.failure_reason
      end
    end
  end
end

if __FILE__ == $PROGRAM_NAME
  ::Skylab::CssConvert::VizTest::Dix.new.invoke
end
