#!/usr/bin/env ruby -w

require_relative '../../core'
require 'pp'

p = Skylab::CssConvert::Grammar::ProgramParser.new
input = $stdin.tty? ? ARGV.join(" ") : $stdin.read.chomp
puts "input:    "+input.inspect
resp = p.parse(input)
# puts "response: "+resp.inspect
puts "num terminal failures: #{p.terminal_failures.size}"
if resp.nil?
  puts "got failure:"
  puts p.failure_reason
else
  puts "got result: "
  PP.pp resp.tree
end
