#!/usr/bin/env ruby -w

# this is kind of a band-aid for a better design, where the "static file
# server" (used in tests)'s PID file is not placed in our tmpdir. with such
# an arrangement, we could just clear our tmpdir on our own without this
# silly dance. mostly this is for [#tm-086]. also relevant to [cs] (toy app)

require 'skylab/system'

tmpdir_path = Skylab::System.services.defaults.dev_tmpdir_path

dir = ::File.dirname tmpdir_path
bn = ::File.basename tmpdir_path

fmt = "#{ bn }.bak.%02d"
d = 0
begin
  d += 1
  use_bn = fmt % d
  available_path = ::File.join dir, use_bn
  if ! ::File.directory? available_path
    break
  end
  if 98 == d
    self._SANITY__too_many__
  end
  redo
end while above

stderr = $stderr
stderr.write "#{ dir }{ #{ bn } => #{ use_bn }}; "

::File.rename tmpdir_path, available_path

stderr.write "mkdir [left one]; "

::Dir.mkdir tmpdir_path

this = "static-file-server.pid"

this_path = ::File.join available_path, this

stderr.write "carry over #{ this }; "

::File.rename this_path, ::File.join( tmpdir_path, this )

stderr.puts " done."
stderr.puts "(don't forget to clear out old tmpdirs eventually)"

# #born.
