#!/usr/bin/env bash

file='z/times'

is_supplemental=''
is_date=''
do_help=''
do_invite=''


if [[ "$1" == '-s' ]] ; then
  is_supplemental=1
  shift
elif [[ "$1" == '-d' ]] ; then
  is_date=1
  shift
fi

if [[ "$#" -eq 0 ]] ; then
  echo "expecting <msg1> .." >&2
  do_invite=1
else
  char=$(echo "$1" | cut -c1)
  if [[ $char == "-" ]] ; then
    if [[ "$1" == '-h' ]] ; then
      do_help=1
    elif [[ "$1" == '--help' ]] ; then
      do_help=1
    else
      echo "unrecognized option: \"${1}\"" >&2
      do_invite=1
    fi
  fi
fi

if [ -n "$do_invite" ] ; then
  echo "use \"$0 -h\" for help" >&2
  exit 5
fi

if [ -n "$do_help" ] ; then
  echo "usage: $0 [-d|-s] msg1 msg2 .." >&2
  echo "" >&2
  echo "description: appends a timestamp line to ${file}" >&2
  echo "" >&2
  echo "options:" >&2
  echo "    -d    date. uglyly include month-day in timestamp" >&2
  echo "    -s    supplemental. only appends message, no timestamp" >&2
  exit 0
fi

if [ ! -f "$file" ] ; then
  echo "for now, file must exist: $file" >&2
  exit 5
fi

if [ -n "$is_date" ] ; then
  da=$(date '+%m-%d %H:%M:%S')
elif [ -n "$is_supplemental" ] ; then
  da='              '
else
  da=$(date '+      %H:%M:%S')
fi

line="  ${da}  $@"

echo "(did: echo \"$line\" >> $file)" >&2

echo "$line" >> "$file"
