#!/usr/bin/env ruby -w

load File.join( File.dirname( File.dirname( __FILE__ ) ),
  '01-representative-renames/02-build-the-manifest' )

_ok = Skylab::GitViz::TestSupport::VCS_Adapters::Git::Story_01::Build_the_manifest.new(

  $stdin, $stdout, $stderr, $PROGRAM_NAME, ARGV, __FILE__ ).session do | sto |

  _, _o, _e, t = sto.popen3_show 'no-such-commit'

  128 == t.value.exitstatus or fail

  sto.init_name_mappings

  _, _o, _e, t = sto.popen3_show_via_story_moniker 'third'

  t.value.exitstatus.zero? or fail

end

exit( _ok ? 0 : 5 )
