#!/usr/bin/env ruby -w

require_relative 'test-support'

module Skylab::Brazen

  module TestSupport_Visual

    lib = ::Skylab::TestSupport::CLI.visual_client

    Client_ = lib::Client

    Branch_ = lib::Branch

    Autoloader_[ self ]

  end
end

Skylab::TestSupport::CLI.visual_client.new(

  $stdin, $stdout, $stderr, ::ARGV, Skylab::Brazen

).execute
