#!/usr/bin/env ruby -w

require_relative '../../test-support'

module ::Skylab::TanMan::TestSupport::Sexp
  class Prototype::Grammars::Grammar70_75_WithPrototype < self::Grammar
    # everything is magic
  end
end

if __FILE__ == $PROGRAM_NAME
  ::Skylab::TanMan::TestSupport::Sexp::Prototype::Grammars::
    Grammar70_75_WithPrototype.new.invoke ::ARGV
end
