#!/usr/bin/env ruby -w

require_relative '../test-support'

module ::Skylab::TanMan::Sexp::TestSupport
  class Prototype::Grammars::Grammar70_75_WithPrototype < self::Grammar
    # everything is magic
  end
end

if __FILE__ == $PROGRAM_NAME
  ::Skylab::TanMan::Sexp::TestSupport::Prototype::Grammars::
    Grammar70_75_WithPrototype.new.invoke ::ARGV
end
