module Skylab::Git::TestSupport

  module Fixture_Modules::Mock_Processes_02

    # (started as generated by git/test/script/story-2/3-other-fixture-code-sketch)

    Build = -> do

      o = Home_.lib_.system_lib::Doubles::Stubbed_System::MockSystem.begin

      o.command_category do |a|
        # in effect don't group commands into categories; there is just one category
        true
      end

      o.command_key do |a|
        # the entire command is its own key
        a
      end

      o.on ["git", "log", "--follow", "--format=%H %ai", "--", "fileA-4"] do

        _out = <<-HERE.unindent
          204-fake-sha 2016-09-11 03:19:43 -0400
          203-fake-sha 2016-09-11 03:19:42 -0400
          202-fake-sha 2016-09-11 03:19:41 -0400
          201-fake-sha 2016-09-11 03:19:40 -0400
        HERE

        [ 0, _out ]
      end

      o.on ["git", "show", "-M", "--format=%D", "204-fake-sha"] do

        _out = <<-HERE.unindent
          HEAD, master

          diff --git a/fileA-3 b/fileA-4
          similarity index 60%
          rename from fileA-3
          rename to fileA-4
          index ef47128..7e429d7 100644
          --- a/fileA-3
          +++ b/fileA-4
          @@ -1,3 +1,3 @@
           lineA1
          -lineA2
          +lineA2-2
           lineA3
        HERE

        [ 0, _out ]
      end

      o.on ["git", "show", "-M", "--format=%D", "203-fake-sha"] do

        _out = <<-HERE.unindent


          diff --git a/fileA-2 b/fileA-3
          similarity index 100%
          rename from fileA-2
          rename to fileA-3
        HERE

        [ 0, _out ]
      end

      o.on ["git", "show", "-M", "--format=%D", "202-fake-sha"] do

        _out = <<-HERE.unindent


          diff --git a/fileA-1 b/fileA-2
          similarity index 100%
          rename from fileA-1
          rename to fileA-2
          diff --git a/fileB-1 b/fileB-1
          index c949afa..4dfe851 100644
          --- a/fileB-1
          +++ b/fileB-1
          @@ -1,3 +1,3 @@
           lineB1
          -lineB2
          +lineB2-2
           lineB3
        HERE

        [ 0, _out ]
      end

      o.on ["git", "show", "-M", "--format=%D", "201-fake-sha"] do

        _out = <<-HERE.unindent


          diff --git a/fileA-1 b/fileA-1
          new file mode 100644
          index 0000000..ef47128
          --- /dev/null
          +++ b/fileA-1
          @@ -0,0 +1,3 @@
          +lineA1
          +lineA2
          +lineA3
          diff --git a/fileB-1 b/fileB-1
          new file mode 100644
          index 0000000..c949afa
          --- /dev/null
          +++ b/fileB-1
          @@ -0,0 +1,3 @@
          +lineB1
          +lineB2
          +lineB3
        HERE

        [ 0, _out ]
      end

      o.finish
    end
  end
end
