module Skylab::Git::TestSupport

  module Fixture_Modules::Mock_Processes_01

    # (started as generated by test/script/story-2/2-fixture-code-sketch

    Build = -> do

      o = Home_.lib_.system_lib::Doubles::Stubbed_System::MockSystem.begin

      o.command_category do |a|
        # in effect don't group commands into categories; there is just one category
        true
      end

      o.command_key do |a|
        # the entire command is its own key
        a
      end

      o.on ["git", "log", "--follow", "--format=%H %ai", "-1", "--", "fileA-2"] do

        _out = <<-HERE.unindent
          fake-sha-1 2016-09-11 03:19:40 -0400
        HERE

        [ 0, _out ]
      end

      o.on ["git", "show", "-M", "--format=%D", "fake-sha-1"] do

        _out = <<-HERE.unindent


          diff --git a/fileA-2 b/fileA-3
          similarity index 100%
          rename from fileA-2
          rename to fileA-3
        HERE

        [ 0, _out ]
      end

      o.on ["git", "log", "--follow", "--format=%H %ai", "-1", "--", "fileA-3"] do

        _out = <<-HERE.unindent
          fake-sha-2 2016-09-11 03:19:40 -0400
        HERE

        [ 0, _out ]
      end

      o.on ["git", "show", "-M", "--format=%D", "fake-sha-2"] do

        _out = <<-HERE.unindent
          HEAD, master

          diff --git a/fileA-3 b/fileA-4
          similarity index 60%
          rename from fileA-3
          rename to fileA-4
          index ef47128..7e429d7 100644
          --- a/fileA-3
          +++ b/fileA-4
          @@ -1,3 +1,3 @@
           lineA1
          -lineA2
          +lineA2-2
           lineA3
        HERE

        [ 0, _out ]
      end

      o.on ["git", "log", "--follow", "--format=%H %ai", "-1", "--", "fileA-4"] do

        _out = <<-HERE.unindent
          fake-sha-2 2016-09-11 03:19:40 -0400
        HERE

        [ 0, _out ]
      end

      o.finish
    end
  end
end
