require_relative '../../../../../test-support'

module Skylab::GitViz::TestSupport

  describe "[gv] VCS adapters - git - models - bundle - actors - build matrix" do

    extend TS_
    use :memoizer_methods
    use :VCS_adapters_git_support_bundle_support

    it "the matrix box's keys are in order" do

      _matrix.order_box.a_.map do | long_SHA |

        long_SHA[ 0, at_( :SHORT_SHA_LENGTH_ ) ]

      end.should eql %w(
        fafa001
        fafa002
        fafa003
        fafa004
        fafa005 )

      # because of the way fake SHA's are generated by the mock normalizer
      # the aboves come out as an arithmetic progression, but this is not
      # by design per se, but rather an unintended aesthetic feature of same.

    end

    it "the matrix box's value are column offsets" do

      bx = _matrix.order_box
      bx.fetch( "fafa001000000000000000000000000000000000" ).should be_zero
      bx.fetch( "fafa005000000000000000000000000000000000" ).should eql 4

    end

    it "the matrix has the bundle" do

      _matrix.bundle.should be_respond_to :ci_box

    end

    shared_subject :_matrix do

      bundle_against_ '/m04/repo'

      expect_no_events

      @bundle.build_matrix_via_repository @repository
    end

    def manifest_path_for_stubbed_FS
      at_ :STORY_04_PATHS_
    end

    def manifest_path_for_stubbed_system
      at_ :STORY_04_COMMANDS_
    end
  end
end

