STORAGE_ADAPTER_CAN_LOAD_DIRECTORIES = False
STORAGE_ADAPTER_CAN_LOAD_SCHEMALESS_SINGLE_FILES = True
STORAGE_ADAPTER_ASSOCIATED_FILENAME_EXTENSIONS = ('.xml',)
STORAGE_ADAPTER_IS_AVAILABLE = False
STORAGE_ADAPTER_UNAVAILABLE_REASON = "it's almost complete but not yet needed"

# #born as nonworking stub
