[item.PBR.attributes]
parent = "8W2"
heading = "gotta learn gcc and basic linking first"
body = """

gotta learn [gcc][1] first.

we had to learn you link C code (with `gcc`):

```(bash)
gcc -o pho/pho-bridge.o -Ipho -c pho/pho-bridge.c
gcc -o pho/main.o -Ipho pho/pho-bridge.o pho/main.c
```



[1] https://www.ntu.edu.sg/home/ehchua/programming/cpp/gcc_make.html
"""

# #born.
