#!/usr/bin/env ruby -w

require_relative '../../test-support'

module Skylab::TanMan::TestSupport::Sexp

  class Grammars::Grammar60_ContentPattern < self::Grammar

    # everything is magic
  end
end

if __FILE__ == $PROGRAM_NAME
  ::Skylab::TanMan::TestSupport::Sexp::Grammars::
    Grammar60_ContentPattern.new.invoke ARGV
end
