"""this is a *100% copy-paste* of the inelegant #[#019.file-type-C]. see."""

import sys


def _():
    import os

    path = os.path
    dn = path.dirname

    a = sys.path
    head = a[0]

    test_sub_dir = dn(__file__)
    top_test_dir = dn(test_sub_dir)
    project_dir = dn(top_test_dir)

    if test_sub_dir == head:
        a[0] = project_dir
    elif project_dir == head:
        # one of two possibilities:
        #
        # 1. unittest is running the whole tree. the specific test files
        # nearby by specific resources in this file.
        #
        # 2. we are running only the nearby file in standalone mode, but
        # we need specific resources here. the nasty thing is happening
        # and file gets loaded twice.
        pass
    else:
        raise Exception('sanity')


_()


import sakin_agac_test._init as x  # noqa: E402
sys.modules[__name__] = x


"""
#todo - generated by tmx/test_support/bin/tmx-test-support-subdivide 0:333:9
(because there's about 9 items in [#408] and we want to occupy the first
1/3 of numberspace for this first pass)
018.5 base class for format adapter itself
055.5 in memory real object stream
092.5 synchronizer for list of names
129.5 item level synch
166.5
203.5
240.5
277.5
314.5
"""

# #copy-pasted.
