[item.38U.attributes]
natural_key="natural key for (FRAG: 38U)"
document_datetime=2019-05-24 18:41:19-04:00
body = """
para 1 line 1
para 1 line 2

para 2 line 1

bullet list:

* Item 1
* Item 2 `with this`
"""
# #born.
