#!/bin/bash


# installs ruby from source to a host using 'rbenv' (like rvm)
#   per https://github.com/sstephenson/rbenv


# Check out rbenv into ~/.rbenv.
cd
git clone git://github.com/sstephenson/rbenv.git .rbenv


# Add ~/.rbenv/bin to your $PATH for access to the rbenv command-line utility.
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.zshrc


# Add rbenv init to your shell to enable shims and autocompletion.
echo 'eval "$(rbenv init -)"' >> ~/.zshrc


echo 'tmx finished installing rbenv'

# Restart your shell so the path changes take effect. You can now begin using rbenv.
exec $SHELL

