name: stm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # At #history-A.2:
  # - 'sealed-class' language feature requires language version >3.0.0.
  # - Pinpointing exact patch level (for reproducability, experimentally, dev)
  sdk: '3.0.5'

dependencies:
  flutter:
    sdk: flutter

  bloc:
  bloc_concurrency:
  equatable:
  http:
  flutter_bloc:
  floor:
  sqflite:
  sqflite_common_ffi:
  english_words:
  provider:

  # (Leaving this in at #history-A.1 despite that codelab doesn't want it)
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:

dev_dependencies:

  build_runner:
  floor_generator:

  test:

  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true

# #history-A.2: bump language version to access 'sealed-class' language feature
# #history-A.1: remove many generated (& informative) comments per codelab
