#!/usr/bin/env zsh

typeset me=$0 ; typeset -a rest ; rest=($*)

source $me/../../../../../../zsh-lib/init-component-node.zsh || return $?

typeset asset_stem
asset_stem=\
$( print $component_node_local_top_dir | sed -E 's_^.+/for-([^/]+)$_\1_' )

typeset vcs
vcs=$( basename $( dirname $( dirname $component_node_local_top_dir ) ) )

typeset asset_output_dir=tmp.$vcs.$asset_stem

if [[ (( 1 < $#rest )) || 'all' == $rest[1] ]] ; then
  # pretty awful: we simply want the output dir as a positional parameter,
  # and the first and only one, passed to the part-building scripts. however,
  # we have to dance around detecting things like when no args are passed
  # so that UI arg parsing errors are triggered when appropriate
  rest+=($asset_output_dir)  # experimental
fi

mock-1-toonsie-doonsie () {
  serr "i don't know, i guess i'm making '$1'"
}

component-node-splay
