#!/usr/bin/env bash

# (at #birth our commit message describes misgivings here)

repo_url="https://github.com/pvieito/PythonKit.git"

if [[ -ne "$1" ]] ; then
  declare -i ec
  if [[ "$1" = "-h" || "$1" = "--help" ]]; then
    ec=0
  else
    echo "unexpected argument: $1" >&2
    ec=1
  fi
  echo "usage: $0"
  if [[ "$ec" = 0 ]] ; then
    echo "description: hackishly \"install\" files we need from $repo_url" >&2
  else
    echo "(a first argument of \"-h\" will give you a description lol)" >&2
  fi
  exit "$ec"
fi

proj_dir="pho"
dest_dir="$proj_dir/PhoGUI"
if [ ! -d "$dest_dir" ] ; then
  echo "run this from the monorepo (dir not found: $dest_dir)" >&2
  exit 1
fi

build_dir="$proj_dir/.build"
if [ ! -d "$build_dir" ] ; then
  echo "mkdir $build_dir" >&2
  mkdir "$build_dir"
fi

co_dir="$build_dir/PythonKit"
if [ -d "$co_dir" ] ;  then
  echo "using existing chekcout: $co_dir" >&2
else
  # commit 29e05a7f7174d9aa64f1b3713fee9f5161b84a51
  # Merge: 9a979cc 2d98efa
  # Author: Pedro José Pereira Vieito <pvieito@gmail.com>
  # Date: Thu May 16 20:48:45 2019 +0200

  echo "git clone $repo_url $co_dir" >&2
  git clone "$repo_url" "$co_dir"
fi

declare -i did_count=0
declare -i total_count=0
files=()
files+=("NumpyConversion.swift")
files+=("Python.swift")
files+=("PythonLibrary+Symbols.swift")
files+=("PythonLibrary.swift")
for file in ${files[@]}; do
  total_count=$(( total_count + 1 ))
  to_path="$dest_dir/$file"
  if [ -e "$to_path" ] ; then
    echo "NOT OVERWRITING, SKIPPING: $to_path" >&2
  else
    from_path="$co_dir/PythonKit/$file"
    echo "cp $from_path $to_path"
    cp "$from_path" "$to_path"
    did_count=$(( did_count + 1 ))
  fi
done

echo "copied $did_count of $total_count files. done."
exit 0

# #birth.
