#!/usr/bin/env zsh  #just-for-syntax-highlighting

typeset -a rest ; rest=($*)

-print-component-node-description () {
  serr
  serr "$( -hdr "description:" ) build specific parts by name"
}

-say-component-node-child-moniker () {
  print part
}

-say-component-node-part-function-name-without-prefix () {
  print -- "${1##$(-say-component-node-function-name-prefix)}"
}

-say-component-node-function-name-prefix () {
  print part-
}

-say-component-node-args () {
  print "$( -component-node-first-arg-moniker ) [remote opts]"
}

component-node-splay
