#!/usr/bin/env ruby -w

require_relative '../../core'

k = ::Skylab::Dependency::StaticFileServer

# sfs = k.new './doc_root', '.', log_level: :info

sfs = k.new(
  ::Skylab::Dependency.dir_pathname.join('test/fixtures'),
  '.'
)

sfs.run
