#!/usr/bin/env ruby -w

  require 'skylab/tmx'

  sout = $stdout

  _st = ::Skylab::TMX.build_sigilized_sidesystem_stream_plus nil

  _st.each do | ss |
    sout.puts "#{ ss.sigil } #{ ss.entry_string }"
  end
