#!/usr/bin/env bash

# ~ begin boilerplate 2

dir=$( dirname $0 )

if [[ ! -e "$dir/00-readme.md" ]] ; then
  echo "something went wrong - was unable to find self"
  exit 5
fi

cd "$dir"

for s in 01-build-the-repo 02-build-the-manifest 03-normalize-the-manifest 04-cleanup  ; do

  "./$s"

  d=$?

  if [ $d -ne 0 ] ; then
    echo "$s failed (exitstatus $d)"
    exit $d
  else
    echo "$s OK"
  fi
done

exit 0

# ~ end
