#!/usr/bin/env ruby -w

require_relative '../../test-support'

module Skylab::Git::TestSupport

      # (see sibling)

      _COMMAND = %w( fileA-4 )

      _CLI = TS_::One_Off_As_Operation::Require[ 'tmx-git-follow-renames' ]

      require 'fileutils'
      ::FileUtils.cd 'fazoozle'

      _Recording = Home_.lib_.system_lib::Doubles::Stubbed_System::Recording

      _real_system = begin ; require 'open3' ; ::Open3 end

      recording = _Recording.via $stdout, _real_system do |rec|

        rec.cache_dont_stream

        rec.wrap_in_module(
          'Skylab::Git::TestSupport',
          'Fixture_Modules::Mock_Processes_02',
        )

        rec.holler_back __FILE__
      end

      _cli = _CLI.new _COMMAND, nil, $stderr, $stderr, %w([gizzi3]) do |cli_|
        cli_.system_by do
          recording
        end
      end

      d = _cli.execute

      recording.receive_done

      if d.nonzero?
        $stderr.puts "(exitstatus: #{ d })"
      end
end
