#!/usr/bin/env ruby -w

require_relative '../test-support'

module ::Skylab::TanMan::Sexp::TestSupport
  class Grammars::Grammar50 < self::Grammar
    # everything is magic
  end
end

if __FILE__ == $PROGRAM_NAME
  ::Skylab::TanMan::Sexp::TestSupport::Grammars::Grammar50.new.invoke ARGV
end
