#!/usr/bin/env zsh  #just-for-syntax-highlighting

part-ohai-description () {
  serr "description: this is a minimal example part"
}

part-ohai-usage () {
  serr "usage: $($partlib_say_invocation_name) -h"
}

-require-partlib

typeset part_func=$0 ; typeset -a rest ; rest=("$*[@]")

typeset adverb asset_output_dir
partlib-parse-adverb-and-asset-output-dir

-partlib-help && return

-partlib-require-asset-output-dir || return $?

--each-winz-command () {
  typeset cmd=$1 cd=$2 triad_callback=$3
  typeset -a a ; a=(${(z)cmd})
  if [[ ! -z  $cd ]] ; then
    cd=/$cd ; typeset dd=/..
  fi

  loud-cd $asset_output_dir$cd || return $?
    typeset o e es ; o==() ; e==()
    serr "${triad_indent}${a[1]} ${(j: :)a[2,-1]}"
    $a[1] $a[2,-1] 1>$o 2>$e
    es=$?
  loud-cd "..$dd"
  $triad_callback $o $e $es
}

troika-lookup-system-commands --each-command --each-winz-command\
  --command-white-filter-regex '\bWINZ\b'\
  --chdir-prefix-white-filter wa-da-da-dir "${rest[@]}"
