require_relative 'my-test-support'

module Skylab::Flex2Treetop::MyTestSupport

  describe "[f2] CLI" do

    extend Top_TS_
    use :expect_stdout_stderr

    # ->

      it "0    with no args - explain what's expected" do
        invoke
        expect :styled, /\Aexpecting <action\>\z/
        expect_usage_and_invite
      end

      it "1.2  with one nonsensical option - explain option not valid" do
        invoke '-x'
        expect %r(\binvalid option: -x\b)i
        expect_invite
      end

      it "2.4   with the -h help flag - display help screen" do
        invoke 'translate', '-h'
        expect_full_help_screen
      end

      def expect_full_help_screen

        on_stream :e

        expect :styled, /\busage: #{ ::Regexp.escape _program_name } .+#{
          }\[-v\] <flex-file> <output-path>\z/

        o = flush_to_content_scanner
        o.expect_nonblank_line
        o.expect_blank_line

        o.expect_header :options

        _count = o.skip_lines_that_match %r(\A[[:space:]])
        ( 12 .. 17 ).should be_include _count

        expect_result_for_success
      end

      it "1    ping simple" do

        invoke 'ping'
        expect 'hello from flex2treetop.'
        expect_no_more_lines
        @exitstatus.should eql :hello_from_flex2treetop
      end

      it "2    ping with argument" do

        invoke 'ping', 'xx'
        expect 'helo:(xx)'
        @exitstatus.should eql :_cheeky_monkey_
      end

      it "2.1  with one giberrsh arg - explain that file is not found" do

        @stdin_for_expect_stdout_stderr = _mock_stdin

        invoke 'trans', 'not-there.txt', '-'
        expect :styled, %r(\bno such <flex-file> - not-there\.txt\z)
        expect_action_invite
      end

      it "1.4  read flex file, write treetop grammar to stdout" do

        @stdin_for_expect_stdout_stderr = _mock_stdin

        invoke 'trans', fixture_flex_( :mini ), '-'
        __expect_all_this
      end

      def __expect_all_this

        @line_stream_for_expect_line =

          sout_serr_line_stream_for_contiguous_lines_on_stream :o

        extend TestSupport_::Expect_line::Test_Context_Instance_Methods

        next_line.should match %r(\A# Autogenerated by fle)

        newline = "\n"
        next_line.should eql newline
        next_line.should eql "# from flex name definitions\n"
        next_line.should eql newline
        next_line.should eql "rule escape__of_lexer__\n"
        next_line.should match %r(\A  unicode__of_lexer__ / )
        next_line.should eql "end\n"

        @exitstatus.should eql :translated
      end

      def invoke * argv
        using_expect_stdout_stderr_invoke_via_argv argv
      end

      def subject_CLI
        Home_::CLI
      end

      define_method :invocation_strings_for_expect_stdout_stderr, -> do
        a =  nil
        -> do
          a ||= [ _program_name ]
        end
      end.call

      def expect_usage_and_invite
        expect_usage
        expect_invite
      end

      def expect_usage
        expect :styled, "usage: #{ _program_name } <action> [..]"
      end

      def expect_invite
        expect :styled, "use '#{ _program_name } -h' for help"
        expect_failed
      end

      def expect_action_invite
        expect :styled, "use '#{ _program_name } translate -h' for help"
        expect_failed
      end

      def result_for_failure_for_expect_stdout_stderr
        Home_::Brazen_::CLI_Support::GENERIC_ERROR_EXITSTATUS
      end

      define_method :_program_name, -> do
        x = 'f2tt'
        -> do x end
      end.call

      def _mock_stdin
        Mock_interactive_stdin_[]
      end

      # <-

  end
end
