#!/usr/bin/env zsh  #just-for-syntax-highlighting

typeset me='build clean'
typeset -a rest ; rest=($*)

-print-component-node-description () {
  serr
  serr "$( -hdr "description:" ) REMOVES GENERATED FIXTURES where available"
}

-say-component-node-child-moniker () {
  print "sub node"
}
-say-each-component-child-node-slug () {
  say-each-child-node-with-a-build-script
}
-component-node-splay-when-sub-command () {
  dispatch-target-to-child-build-script clean $rest
}
-component-node-splay-when-help-not-requested () {
  dispatch-target-and-args-to-all clean "${*[@]}"
}

component-node-splay
