#!/usr/bin/env zsh  #just-for-syntax-highlighting

typeset me='build all'
typeset -a rest ; rest=($*)

-print-component-node-description () {
  serr
  serr "$( -hdr "description:" ) issues a \"build all\" to all sub-nodes\
 that have a build script."
  serr "             any provided args are passed down to each node as well."
}
-say-component-node-args () {
  print "[..]"
}
-say-component-node-child-moniker-plural () {
  print "(message are sent to)"
}
-say-each-component-child-node-slug () {
  say-each-child-node-with-a-build-script
}
-component-node-splay-when-help-not-requested () {
  dispatch-target-and-args-to-all all "${*[@]}"
}

component-node-splay
