STORAGE_ADAPTER_CAN_LOAD_DIRECTORIES = True
STORAGE_ADAPTER_CAN_LOAD_SCHEMALESS_SINGLE_FILES = False
STORAGE_ADAPTER_IS_AVAILABLE = False
STORAGE_ADAPTER_UNAVAILABLE_REASON = "it's a placeholder stub"

# #born as nonworking stub
